#!/bin/sh /etc/rc.common
# Init script for PigeonMesh Cloud Bridge sync service

START=99
USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command /bin/sh /usr/bin/pm-bridge-sync.sh
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param respawn
    procd_close_instance
}
